"""followers

Revision ID: 362bf7a9b712
Revises: 79d7ee110300
Create Date: 2018-06-17 18:12:45.122266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362bf7a9b712'
down_revision = '79d7ee110300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
